---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: dubbo-consumer-demo
        provider: jkube
        version: 1.3.0-SNAPSHOT
        group: com.jdcloud.jmsf
      name: dubbo-consumer-demo
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        matchLabels:
          app: dubbo-consumer-demo
          provider: jkube
          group: com.jdcloud.jmsf
      template:
        metadata:
          labels:
            app: dubbo-consumer-demo
            provider: jkube
            version: 1.3.0-SNAPSHOT
            group: com.jdcloud.jmsf
        spec:
          containers:
            - env:
                - name: JMESH_ENABLE_MESH
                  value: "true"
                - name: JMESH_MESH_GROUP
                  value: mesh01
                - name: JMESH_REGISTRY_HOST
                  value: consul-service.istio-system.svc
                - name: JMESH_REGISTRY_PORT
                  value: "8500"
                - name: JMESH_REGISTRY_TOKEN
                  value: 50ab30c3-1d91-ab98-e81d-78b3ce1f2405
                - name: JMESH_CONFIG_HOST
                  value: consul-service.istio-system.svc
                - name: JMESH_CONFIG_PORT
                  value: "8500"
                - name: JMESH_CONFIG_TOKEN
                  value: 50ab30c3-1d91-ab98-e81d-78b3ce1f2405
                - name: JMESH_SERVICE_APP
                  value: jmsf-dubbo-consumer-app
                - name: JMESH_SERVICE_CLUSTER
                  value: cluster1
                - name: JMESH_SERVICE_DEPLOYMENT
                  value: dep1
                - name: JMESH_SERVICE_GROUP
                  value: group1
                - name: JMESH_SERVICE_ID
                  value: jmsf-dubbo-consumer-svc
                - name: JMESH_SERVICE_NAMESPACE
                  value: default
                - name: JMESH_SERVICE_VERSION
                  value: v1.0
                - name: ML_AZ
                  value: zone1
                - name: organization
                  value: JMSF
                - name: projectname
                  value: JMSF - MeshWare Dubbo Demo - Consumer
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: HOSTNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              image: hub-vpc.jdcloud.com/mesh/jmsf-dubbo-consumer:1.3.0-SNAPSHOT
              imagePullPolicy: Always
              name: jmsf-dubbo-consumer-demo
              securityContext:
                privileged: false